-- Generated by Oracle SQL Developer Data Modeler 22.2.0.165.1149
--   at:        2023-05-03 15:47:27 AEST
--   site:      Oracle Database 12c
--   type:      Oracle Database 12c

set echo on
spool cui_schema2_output.txt

DROP TABLE authority CASCADE CONSTRAINTS;

DROP TABLE bin CASCADE CONSTRAINTS;

DROP TABLE bin_type CASCADE CONSTRAINTS;

DROP TABLE collection_report CASCADE CONSTRAINTS;

DROP TABLE contract CASCADE CONSTRAINTS;

DROP TABLE contract_bintype CASCADE CONSTRAINTS;

DROP TABLE contract_wastetype CASCADE CONSTRAINTS;

DROP TABLE driver CASCADE CONSTRAINTS;

DROP TABLE owner CASCADE CONSTRAINTS;

DROP TABLE property CASCADE CONSTRAINTS;

DROP TABLE property_owner CASCADE CONSTRAINTS;

DROP TABLE street CASCADE CONSTRAINTS;

DROP TABLE truck CASCADE CONSTRAINTS;

DROP TABLE truck_driver CASCADE CONSTRAINTS;

DROP TABLE waste_type CASCADE CONSTRAINTS;

-- predefined type, no DDL - MDSYS.SDO_GEOMETRY

-- predefined type, no DDL - XMLTYPE

CREATE TABLE authority (
    lo_auth_name  CHAR(30) NOT NULL,
    la_ceo_gname  CHAR(30) NOT NULL,
    la_ceo_fname  CHAR(30) NOT NULL,
    la_contact_no CHAR(15) NOT NULL,
    la_total_area NUMBER(9, 2) NOT NULL,
    la_type       CHAR(1) NOT NULL
);

ALTER TABLE authority
    ADD CONSTRAINT "local authority type" CHECK ( la_type IN ( 'B', 'C', 'D', 'S', 'T'
    ) );

COMMENT ON COLUMN authority.lo_auth_name IS
    'local authority name';

COMMENT ON COLUMN authority.la_ceo_gname IS
    'local authority ceo given name 
';

COMMENT ON COLUMN authority.la_ceo_fname IS
    'local authority ceo first name ';

COMMENT ON COLUMN authority.la_contact_no IS
    'local authority contact number';

COMMENT ON COLUMN authority.la_total_area IS
    'local authority total area';

ALTER TABLE authority ADD CONSTRAINT authority_pk PRIMARY KEY ( lo_auth_name );

CREATE TABLE bin (
    bin_rfid           CHAR(30) NOT NULL,
    bin_suply_date     DATE NOT NULL,
    bin_reson_replcmnt CHAR(2) NOT NULL,
    strt_num           CHAR(20) NOT NULL,
    strt_name          CHAR(30) NOT NULL,
    street_id          VARCHAR2(10) NOT NULL,
    lo_auth_name       CHAR(30) NOT NULL
);

ALTER TABLE bin
    ADD CONSTRAINT "bin reason for replacement" CHECK ( bin_reson_replcmnt IN ( 'BF',
    'DO', 'DW', 'ST' ) );

COMMENT ON COLUMN bin.bin_rfid IS
    'Bin rfid';

COMMENT ON COLUMN bin.bin_suply_date IS
    'Bin Supply Date';

COMMENT ON COLUMN bin.strt_num IS
    'Street number';

COMMENT ON COLUMN bin.street_id IS
    'Street id';

COMMENT ON COLUMN bin.lo_auth_name IS
    'local authority name';

ALTER TABLE bin ADD CONSTRAINT bin_pk PRIMARY KEY ( bin_rfid );

CREATE TABLE bin_type (
    bin_size       NUMBER(9, 2),
    bin_cost       NUMBER(9, 2),
    bin_type       CHAR(20) NOT NULL,
    waste_weight   NUMBER(3, 2),
    waste_overload CHAR(1),
    bin_rfid       CHAR(30) NOT NULL,
    waste_type_id  CHAR(20) NOT NULL
);

ALTER TABLE bin_type
    ADD CONSTRAINT "waste overload" CHECK ( waste_overload IN ( 'N', 'Y' ) );

COMMENT ON COLUMN bin_type.bin_size IS
    'Bin Size';

COMMENT ON COLUMN bin_type.bin_cost IS
    'bin cost';

COMMENT ON COLUMN bin_type.bin_type IS
    'bin type';

COMMENT ON COLUMN bin_type.waste_weight IS
    'waste weight';

COMMENT ON COLUMN bin_type.waste_overload IS
    'waste overload';

COMMENT ON COLUMN bin_type.bin_rfid IS
    'Bin rfid';

COMMENT ON COLUMN bin_type.waste_type_id IS
    'waste type id';

ALTER TABLE bin_type
    ADD CONSTRAINT bin_type_pk PRIMARY KEY ( bin_type,
                                             bin_rfid,
                                             waste_type_id );

CREATE TABLE collection_report (
    "date"        DATE NOT NULL,
    contrct_num   CHAR(20) NOT NULL,
    waste_type_id CHAR(20) NOT NULL,
    truck_vin     CHAR(20) NOT NULL,
    driver_num    CHAR(10) NOT NULL
);

COMMENT ON COLUMN collection_report."date" IS
    'Date';

COMMENT ON COLUMN collection_report.contrct_num IS
    'Contract num';

COMMENT ON COLUMN collection_report.waste_type_id IS
    'waste type id';

COMMENT ON COLUMN collection_report.truck_vin IS
    'truck vehicle identification number';

COMMENT ON COLUMN collection_report.driver_num IS
    'driver number';

ALTER TABLE collection_report
    ADD CONSTRAINT collection_report_pk PRIMARY KEY ( "date",
                                                      contrct_num,
                                                      waste_type_id );

CREATE TABLE contract (
    contrct_num       CHAR(20) NOT NULL,
    contrct_strt_date DATE NOT NULL,
    contrct_end_date  DATE NOT NULL,
    lo_auth_name      CHAR(30) NOT NULL
);

COMMENT ON COLUMN contract.contrct_num IS
    'Contract num';

COMMENT ON COLUMN contract.contrct_strt_date IS
    'Contract start date';

COMMENT ON COLUMN contract.contrct_end_date IS
    'contract end date';

COMMENT ON COLUMN contract.lo_auth_name IS
    'local authority name';

ALTER TABLE contract ADD CONSTRAINT contract_pk PRIMARY KEY ( contrct_num );

CREATE TABLE contract_bintype (
    contrct_num       CHAR(20) NOT NULL,
    stndrd_suply_cost NUMBER(9, 2),
    contrct_num1      CHAR(20) NOT NULL,
    bin_type          CHAR(20) NOT NULL,
    bin_rfid          CHAR(30) NOT NULL,
    waste_type_id     CHAR(20) NOT NULL
);

COMMENT ON COLUMN contract_bintype.contrct_num IS
    'contract number';

COMMENT ON COLUMN contract_bintype.stndrd_suply_cost IS
    'standard supply cost';

COMMENT ON COLUMN contract_bintype.contrct_num1 IS
    'Contract num';

COMMENT ON COLUMN contract_bintype.bin_type IS
    'bin type';

COMMENT ON COLUMN contract_bintype.bin_rfid IS
    'Bin rfid';

COMMENT ON COLUMN contract_bintype.waste_type_id IS
    'waste type id';

ALTER TABLE contract_bintype ADD CONSTRAINT contract_bintype_pk PRIMARY KEY ( contrct_num
,
                                                                              contrct_num1
                                                                              );

CREATE TABLE contract_wastetype (
    contrct_collectn_cost NUMBER(9, 2) NOT NULL,
    collectn_freqncy      CHAR(1) NOT NULL,
    contrct_num           CHAR(20) NOT NULL,
    waste_type_id         CHAR(20) NOT NULL
);

COMMENT ON COLUMN contract_wastetype.contrct_collectn_cost IS
    'contract collection cost';

COMMENT ON COLUMN contract_wastetype.collectn_freqncy IS
    'collection frequency';

COMMENT ON COLUMN contract_wastetype.contrct_num IS
    'Contract num';

COMMENT ON COLUMN contract_wastetype.waste_type_id IS
    'waste type id';

ALTER TABLE contract_wastetype ADD CONSTRAINT contract_wastetype_pk PRIMARY KEY ( contrct_num
,
                                                                                waste_type_id
                                                                                );

CREATE TABLE driver (
    driver_num     CHAR(10) NOT NULL,
    license_num    CHAR(20) NOT NULL,
    driver_fname   CHAR(20) NOT NULL,
    driver_lname   CHAR(20) NOT NULL,
    driver_dob     DATE NOT NULL,
    driver_tfn     CHAR(10) NOT NULL,
    driver_contact CHAR(10) NOT NULL
);

COMMENT ON COLUMN driver.driver_num IS
    'driver number';

COMMENT ON COLUMN driver.license_num IS
    'license number';

COMMENT ON COLUMN driver.driver_fname IS
    'driver first name';

COMMENT ON COLUMN driver.driver_lname IS
    'driver last name';

COMMENT ON COLUMN driver.driver_dob IS
    'driver date of birth';

COMMENT ON COLUMN driver.driver_tfn IS
    'driver tax file number';

COMMENT ON COLUMN driver.driver_contact IS
    'driver contact number';

ALTER TABLE driver ADD CONSTRAINT driver_pk PRIMARY KEY ( driver_num );

CREATE TABLE owner (
    ownr_id    CHAR(20) NOT NULL,
    ownr_name  CHAR(30) NOT NULL,
    ownr_email CHAR(30),
    ownr_num   NUMBER(9, 2) NOT NULL
);

COMMENT ON COLUMN owner.ownr_id IS
    'Owner id';

COMMENT ON COLUMN owner.ownr_name IS
    'owner name';

COMMENT ON COLUMN owner.ownr_email IS
    'owner email id';

COMMENT ON COLUMN owner.ownr_num IS
    'owner number';

ALTER TABLE owner ADD CONSTRAINT owner_pk PRIMARY KEY ( ownr_id );

CREATE TABLE property (
    strt_num     CHAR(20) NOT NULL,
    strt_name    CHAR(30) NOT NULL,
    street_id    VARCHAR2(10) NOT NULL,
    lo_auth_name CHAR(30) NOT NULL
);

COMMENT ON COLUMN property.strt_num IS
    'Street number';

COMMENT ON COLUMN property.street_id IS
    'Street id';

COMMENT ON COLUMN property.lo_auth_name IS
    'local authority name';

ALTER TABLE property
    ADD CONSTRAINT property_pk PRIMARY KEY ( strt_num,
                                             strt_name,
                                             street_id,
                                             lo_auth_name );

CREATE TABLE property_owner (
    strt_num     CHAR(20) NOT NULL,
    strt_name    CHAR(30) NOT NULL,
    street_id    VARCHAR2(10) NOT NULL,
    lo_auth_name CHAR(30) NOT NULL,
    ownr_id      CHAR(20) NOT NULL
);

COMMENT ON COLUMN property_owner.strt_num IS
    'Street number';

COMMENT ON COLUMN property_owner.street_id IS
    'Street id';

COMMENT ON COLUMN property_owner.lo_auth_name IS
    'local authority name';

COMMENT ON COLUMN property_owner.ownr_id IS
    'Owner id';

CREATE TABLE street (
    street_id     VARCHAR2(10) NOT NULL,
    street_name   CHAR(30) NOT NULL,
    strt_in_metrs NUMBER(9, 2) NOT NULL,
    strt_rs_type  CHAR(30) NOT NULL,
    strt_lane_no  CHAR(10),
    lo_auth_name  CHAR(30) NOT NULL
);

ALTER TABLE street
    ADD CONSTRAINT "road surface type" CHECK ( strt_rs_type IN ( 'A', 'C', 'U' ) );

COMMENT ON COLUMN street.street_id IS
    'Street id';

COMMENT ON COLUMN street.street_name IS
    'Street name';

COMMENT ON COLUMN street.strt_in_metrs IS
    'Street in meters';

COMMENT ON COLUMN street.strt_rs_type IS
    'Street road surface type';

COMMENT ON COLUMN street.strt_lane_no IS
    'Street lane number';

COMMENT ON COLUMN street.lo_auth_name IS
    'local authority name';

ALTER TABLE street ADD CONSTRAINT street_pk PRIMARY KEY ( street_id,
                                                          lo_auth_name );

CREATE TABLE truck (
    truck_vin       CHAR(20) NOT NULL,
    truck_rego_num  CHAR(20) NOT NULL,
    truck_make_year CHAR(20) NOT NULL,
    truck_model     CHAR(20) NOT NULL,
    truck_year      DATE NOT NULL
);

COMMENT ON COLUMN truck.truck_vin IS
    'truck vehicle identification number';

COMMENT ON COLUMN truck.truck_rego_num IS
    'truck rego number
';

COMMENT ON COLUMN truck.truck_make_year IS
    'truck make year';

COMMENT ON COLUMN truck.truck_model IS
    'truck model ';

COMMENT ON COLUMN truck.truck_year IS
    'truck year';

ALTER TABLE truck ADD CONSTRAINT truck_pk PRIMARY KEY ( truck_vin );

CREATE TABLE truck_driver (
    truck_vin     CHAR(20) NOT NULL,
    driver_num    CHAR(10) NOT NULL,
    date_approval DATE NOT NULL
);

COMMENT ON COLUMN truck_driver.truck_vin IS
    'truck vehicle identification number';

COMMENT ON COLUMN truck_driver.driver_num IS
    'driver number';

COMMENT ON COLUMN truck_driver.date_approval IS
    'date of approval';

ALTER TABLE truck_driver ADD CONSTRAINT truck_driver_pk PRIMARY KEY ( truck_vin,
                                                                      driver_num );

CREATE TABLE waste_type (
    waste_type_id       CHAR(20) NOT NULL,
    waste_type_descript CHAR(40)
);

COMMENT ON COLUMN waste_type.waste_type_id IS
    'waste type id';

COMMENT ON COLUMN waste_type.waste_type_descript IS
    'waste type description ';

ALTER TABLE waste_type ADD CONSTRAINT waste_type_pk PRIMARY KEY ( waste_type_id );

ALTER TABLE bin
    ADD CONSTRAINT bin_property_fk FOREIGN KEY ( strt_num,
                                                 strt_name,
                                                 street_id,
                                                 lo_auth_name )
        REFERENCES property ( strt_num,
                              strt_name,
                              street_id,
                              lo_auth_name );

ALTER TABLE bin_type
    ADD CONSTRAINT bin_type_bin_fk FOREIGN KEY ( bin_rfid )
        REFERENCES bin ( bin_rfid );

ALTER TABLE bin_type
    ADD CONSTRAINT bin_type_waste_type_fk FOREIGN KEY ( waste_type_id )
        REFERENCES waste_type ( waste_type_id );

--  ERROR: FK name length exceeds maximum allowed length(30) 
ALTER TABLE collection_report
    ADD CONSTRAINT collection_report_contract_wastetype_fk FOREIGN KEY ( contrct_num,
                                                                         waste_type_id
                                                                         )
        REFERENCES contract_wastetype ( contrct_num,
                                        waste_type_id );

--  ERROR: FK name length exceeds maximum allowed length(30) 
ALTER TABLE collection_report
    ADD CONSTRAINT collection_report_truck_driver_fk FOREIGN KEY ( truck_vin,
                                                                   driver_num )
        REFERENCES truck_driver ( truck_vin,
                                  driver_num );

ALTER TABLE contract
    ADD CONSTRAINT contract_authority_fk FOREIGN KEY ( lo_auth_name )
        REFERENCES authority ( lo_auth_name );

ALTER TABLE contract_bintype
    ADD CONSTRAINT contract_bintype_bin_type_fk FOREIGN KEY ( bin_type,
                                                              bin_rfid,
                                                              waste_type_id )
        REFERENCES bin_type ( bin_type,
                              bin_rfid,
                              waste_type_id );

ALTER TABLE contract_bintype
    ADD CONSTRAINT contract_bintype_contract_fk FOREIGN KEY ( contrct_num1 )
        REFERENCES contract ( contrct_num );

ALTER TABLE contract_wastetype
    ADD CONSTRAINT contract_wastetype_contract_fk FOREIGN KEY ( contrct_num )
        REFERENCES contract ( contrct_num );

--  ERROR: FK name length exceeds maximum allowed length(30) 
ALTER TABLE contract_wastetype
    ADD CONSTRAINT contract_wastetype_waste_type_fk FOREIGN KEY ( waste_type_id )
        REFERENCES waste_type ( waste_type_id );

ALTER TABLE property_owner
    ADD CONSTRAINT property_owner_owner_fk FOREIGN KEY ( ownr_id )
        REFERENCES owner ( ownr_id );

ALTER TABLE property_owner
    ADD CONSTRAINT property_owner_property_fk FOREIGN KEY ( strt_num,
                                                            strt_name,
                                                            street_id,
                                                            lo_auth_name )
        REFERENCES property ( strt_num,
                              strt_name,
                              street_id,
                              lo_auth_name );

ALTER TABLE property
    ADD CONSTRAINT property_street_fk FOREIGN KEY ( street_id,
                                                    lo_auth_name )
        REFERENCES street ( street_id,
                            lo_auth_name );

ALTER TABLE street
    ADD CONSTRAINT street_authority_fk FOREIGN KEY ( lo_auth_name )
        REFERENCES authority ( lo_auth_name );

ALTER TABLE truck_driver
    ADD CONSTRAINT truck_driver_driver_fk FOREIGN KEY ( driver_num )
        REFERENCES driver ( driver_num );

ALTER TABLE truck_driver
    ADD CONSTRAINT truck_driver_truck_fk FOREIGN KEY ( truck_vin )
        REFERENCES truck ( truck_vin );

set echo off
spool off

-- Oracle SQL Developer Data Modeler Summary Report: 
-- 
-- CREATE TABLE                            15
-- CREATE INDEX                             0
-- ALTER TABLE                             34
-- CREATE VIEW                              0
-- ALTER VIEW                               0
-- CREATE PACKAGE                           0
-- CREATE PACKAGE BODY                      0
-- CREATE PROCEDURE                         0
-- CREATE FUNCTION                          0
-- CREATE TRIGGER                           0
-- ALTER TRIGGER                            0
-- CREATE COLLECTION TYPE                   0
-- CREATE STRUCTURED TYPE                   0
-- CREATE STRUCTURED TYPE BODY              0
-- CREATE CLUSTER                           0
-- CREATE CONTEXT                           0
-- CREATE DATABASE                          0
-- CREATE DIMENSION                         0
-- CREATE DIRECTORY                         0
-- CREATE DISK GROUP                        0
-- CREATE ROLE                              0
-- CREATE ROLLBACK SEGMENT                  0
-- CREATE SEQUENCE                          0
-- CREATE MATERIALIZED VIEW                 0
-- CREATE MATERIALIZED VIEW LOG             0
-- CREATE SYNONYM                           0
-- CREATE TABLESPACE                        0
-- CREATE USER                              0
-- 
-- DROP TABLESPACE                          0
-- DROP DATABASE                            0
-- 
-- REDACTION POLICY                         0
-- TSDP POLICY                              0
-- 
-- ORDS DROP SCHEMA                         0
-- ORDS ENABLE SCHEMA                       0
-- ORDS ENABLE OBJECT                       0
-- 
-- ERRORS                                   3
-- WARNINGS                                 0
